language: python
notifications:
    email: false
install:
    - pip install -r requirements_dev.txt
    - python setup.py develop
services:
    - postgresql
before_script:
    - psql -c "create user t2user with password 't2pass';" -U postgres
    - psql -c "create database t2db_test with owner t2user;"
    - flake8 .
script:
    - make test
after_success:
    - coveralls
