version: '3.5'

services:
  web:
    build: .
    command: gunicorn app:app -b 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql+psycopg2://t2user:t2pass@db/t2db
      - SENDGRID_API_KEY=empty
      - GOOGLE_API_KEY=empty
      - FIREBASE_AUTH=empty

  db:
    image: postgres:9.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=t2user
      - POSTGRES_PASSWORD=t2pass
      - POSTGRES_DB=t2db
    ports:
      - 5433:5432
volumes:
  postgres_data:
